name: tests

on: [push, pull_request, workflow_dispatch]


jobs:
  test:
  
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.10"]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Inject API keys
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: echo -en "${{ secrets.KEYS_INI }}" >> keys.ini
          macos: echo -en "${{ secrets.KEYS_INI }}" >> keys.ini
          windows: New-Item "keys.ini" -ItemType File -Value "${{ secrets.KEYS_INI }}"

      - name: Install test dependencies
        run: pip install pytest-cov coverage-badge

      - name: Run tests with pytest
        run: python -m pytest --cov
        
      - name: Update coverage badge (Ubuntu only)
        if: ${{ ( success() || failure() ) && matrix.os == 'ubuntu-latest' && matrix.python == '3.10' }}
        continue-on-error: true
        run: |
          coverage-badge -o tests/badge.svg -f
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/badge.svg
          git commit --author="Prerit Das <preritdas@gmail.com>" -m "Update coverage badge after unit tests."
          git fetch && git pull && git push
